# Generated by Django 5.0.1 on 2024-02-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
